# Generated by Django 4.0.3 on 2022-04-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_delete_projection'),
        ('projections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.ticket'),
        ),
    ]
