# Generated by Django 4.0.3 on 2022-04-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_delete_projection'),
        ('projections', '0002_projection_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='ticket',
        ),
        migrations.AddField(
            model_name='projection',
            name='ticket',
            field=models.ManyToManyField(to='movies.ticket'),
        ),
    ]
