# Generated by Django 4.0.3 on 2022-03-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_auth', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
