# Generated by Django 4.0.3 on 2022-04-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_auth', '0008_cinemauser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemauser',
            name='is_active',
        ),
    ]
