# Generated by Django 4.0.3 on 2022-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_auth', '0009_remove_cinemauser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemauser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
