# Generated by Django 4.0.3 on 2022-03-05 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('movies', models.ManyToManyField(to='movies.movie')),
            ],
        ),
    ]
