# Generated by Django 4.0.3 on 2022-03-06 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='city',
            new_name='country',
        ),
    ]
