# Generated by Django 4.0.3 on 2022-03-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_rename_city_actor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='unknown.jpg', upload_to='actor_images/'),
        ),
    ]
