# Generated by Django 4.0.3 on 2022-03-05 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Criminal', 'Criminal'), ('Thriller', 'Thriller'), ('Action', 'Action'), ('Fantasy', 'Fantasy'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Historical', 'Historical'), ('Documentary', 'Documentary')], max_length=11, validators=[django.core.validators.MinLengthValidator(5)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('duration', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
