# Generated by Django 4.0.3 on 2022-03-06 09:16

import cinema_app.movies.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2), cinema_app.movies.validators.validate_word_start_with_capital_letter]),
        ),
    ]
