# Generated by Django 4.0.3 on 2022-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_category_alter_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie_images/default.jpg', upload_to='movie_images'),
        ),
    ]
