# Generated by Django 4.0.3 on 2022-03-12 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_name_movie_title_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Criminal', 'Criminal'), ('Thriller', 'Thriller'), ('Action', 'Action'), ('Fantasy', 'Fantasy'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Historical', 'Historical'), ('Documentary', 'Documentary')], default='Select genre', max_length=11, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
