# Generated by Django 4.0.3 on 2022-03-20 14:34

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
