# Generated by Django 4.0.3 on 2022-03-20 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='ratings',
        ),
    ]
