# Generated by Django 4.0.3 on 2022-04-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_alter_movie_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['id']},
        ),
    ]
