# Generated by Django 4.0.3 on 2022-04-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_projections_delete_movietime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='projection_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.projections'),
        ),
    ]
