# Generated by Django 4.0.3 on 2022-04-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_ticket_projection_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projections',
            options={'verbose_name': 'Projection', 'verbose_name_plural': 'Projections'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='projection_time',
        ),
    ]
