# Generated by Django 4.0.3 on 2022-04-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_projections_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projections',
            name='day_of_the_week',
        ),
    ]
