# Generated by Django 4.0.3 on 2022-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_cart', '0013_alter_item_projection'),
        ('movies', '0023_projection_remove_projections_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projections',
        ),
        migrations.AddField(
            model_name='projection',
            name='movie',
            field=models.ManyToManyField(to='movies.movie'),
        ),
    ]
