# Generated by Django 4.0.3 on 2022-04-11 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_delete_projections_projection_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='projection',
            name='day_of_the_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=9, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
