# Generated by Django 4.0.3 on 2022-04-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_projection_day_of_the_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='movie',
        ),
    ]
