# Generated by Django 4.0.3 on 2022-04-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_remove_projection_movie'),
        ('tickets_cart', '0014_alter_item_projection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projection',
        ),
    ]
