# Generated by Django 4.0.3 on 2022-04-11 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_delete_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Criminal', 'Criminal'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Historical', 'Historical'), ('Documentary', 'Documentary')], max_length=11, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='genre'),
        ),
    ]
