# Generated by Django 4.0.3 on 2022-04-03 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_cart', '0002_remove_cart_total_alter_cart_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 19, 33, 2, 681016)),
        ),
    ]
