# Generated by Django 4.0.3 on 2022-04-04 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_cart', '0003_alter_cart_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 18, 7, 0, 351863)),
        ),
    ]
