# Generated by Django 4.0.3 on 2022-04-05 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_cart', '0006_alter_cart_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 16, 59, 59, 502713)),
        ),
    ]
