# Generated by Django 4.0.3 on 2022-04-05 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_cart', '0007_alter_cart_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 17, 8, 52, 884374)),
        ),
    ]
