# Generated by Django 4.0.3 on 2022-04-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_projection_remove_projections_movie'),
        ('tickets_cart', '0012_item_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='projection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.projection'),
        ),
    ]
