# Generated by Django 4.0.3 on 2022-04-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projections', '0001_initial'),
        ('tickets_cart', '0013_alter_item_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='projection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projections.projection'),
        ),
    ]
